apiVersion: v1
kind: Service
metadata:
  name: wiremock-service
  namespace: wiremock-namespace
  labels:
    app: gateway-demo-only
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: wiremock
  type: ClusterIP
