server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

    kubernetes:
      discovery:
        all-namespaces: true
        # narrow the returned services to only our ones.
        service-labels:
          app: gateway-demo-only

management:
  endpoints:
    web:
      exposure:
        include: gateway, health
  endpoint:
    gateway:
      enabled: true
